[package]
name = "http_tide"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.13.0", features = ["attributes"] }
serde = { version = "1.0.210", features = ["derive"] }
tide = "0.16.0"
